### ISSUE TITLE
Remove ZWeb3 from the lib public API

### ISSUE THREAD

**Issue by pcowgill** [OpenZeppelin/openzeppelin-sdk#1047]
As discussed previously in this issue https://github.com/zeppelinos/zos/issues/591

**Comment by pcowgill** [comment]
@spalladino Am I correct in thinking that the tests in the [examples dir](https://github.com/zeppelinos/zos/tree/master/examples) will be moving away from using ZWeb3 in the future? Thanks!

**Comment by spalladino** [comment]
Hey @pcowgill! We may continue to use ZWeb3 internally, as it's useful as an abstraction layer on top of web3 in case we need to monkeypatch anything, or even switch between different versions. What we will most likely change is `zos-lib` public API by making initialization smoother, so the user does not need to know about or use it.

**Comment by pcowgill** [comment]
Makes sense! Thanks, that answer is very helpful.

In that case maybe we can rename this issue to be about removing it from the public API and example test suites?

**Comment by spalladino** [comment]
Updated!

**Comment by spalladino** [comment]
Closing in favour of #1308
