### ISSUE TITLE
zos.json shows "zosversion": "2.2" when created using zos init with ZeppelinOS 2.4

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1055]
Initialize zos using `zos init` and the created `zos.json` file configuration states `"zosversion": "2.2"`

**💻 Environment**
`npx zos --version` 2.4.0
`node --version` v10.16.0
Windows Subsystem for Linux - Ubuntu 18.04.2 LTS

**📝 Details**

Using ZeppelinOS 2.4 `zos init` results in a `zos.json` file with the zos version as 2.2.

```
{
  "zosversion": "2.2",
  "contracts": {},
  "dependencies": {},
  "name": "test",
  "version": "1.0.0"
}
```

**🔢 Code to reproduce bug**

`mkdir test`
`cd test`
`npm init -y`
`npm i zos`
`npx zos init`

**Comment by abcoathup** [comment]
Documentation states `zosversion` indicates the major version of ZeppelinOS.

>https://docs.zeppelinos.org/docs/configuration.html
The field zosversion indicates the major version of ZeppelinOS you are using: zos.json files with a different major version are automatically rejected.

**Comment by jcarpanelli** [comment]
Hi @abcoathup! The `zosversion` field in the `zos.json` file is actually a manifest version. It doesn't change when a zos version is released but when we introduce changes into the structure of the `zos.json` file.
We are changing this field from `zosversion` to `manifestVersion` for `v2.5.0`. 

Anyways, it seems that we are not explaining this right in the docsite. I'll tag it as a documentation issue :+1:.

Related to https://github.com/zeppelinos/zos/issues/1008.

**Comment by spalladino** [comment]
Renamed this field to manifestVersion to avoid confusion
