### ISSUE TITLE
Example "truffle-migrate": Error: zos version identifier not found in zos.json. This means the project was built with an older version of zos (1.x), and needs to be upgraded

### ISSUE THREAD

**Issue by itinance** [OpenZeppelin/openzeppelin-sdk#1057]
On a fresh install (including "npm install" and a running ganache-cli), running the command

`truffle migrate --network local`

will give the following error:

> Error: Error: Error: zos version identifier not found in zos.json. This means the project was built with an older version of zos (1.x), and needs to be upgraded. Please refer to the documentation at https://docs.zeppelinos.org for more info.
>     at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> Truffle v5.0.21 (core: 5.0.21)
> Node v10.16.0

```
$ zos --version
2.4.0
```

**Comment by itinance** [comment]
Will be fixed with https://github.com/zeppelinos/zos/pull/1058 (at least vor zos <= 2.4)

**Comment by jcarpanelli** [comment]
As mentioned in https://github.com/zeppelinos/zos/pull/1058:
We are in the middle of a renaming migration in the `master` branch (See https://github.com/zeppelinos/zos/issues/925 and [this](https://github.com/zeppelinos/zos/blob/8647b223c84faf30e2ab0546994c5a87d1e830a6/design/renaming.md)). I would suggest you to work with the same examples but in the [release/2.4](https://github.com/zeppelinos/zos/tree/release/2.4) branch, which does not have these naming changes.

**Comment by spalladino** [comment]
Fixed
