### ISSUE TITLE
Configurable timeout on web3

### ISSUE THREAD

**Issue by itinance** [OpenZeppelin/openzeppelin-sdk#1065]
My token deployment on Main network timedout after 750 seconds with `zos create`, although everything worked fast on Ropsten. According to the transaction-id, the whole process was confirmed on public blockchain after 830 seconds.

1. Can we increase this timeout-value somehow, maybe as an argument on CLI?

2. Since we use the Proxy contracts, I’m not sure which contract address I can use as the token-address for my CrowdSale-Crontract after such a timeout.

Is this the “to”-address on Etherscan.io that is labeled with “contract”?
Example: https://etherscan.io/tx/0xe56d6fb13da4acaba165c7d9fdaba29441feadf857d64e9bb88cdd78ebb9c219

**Comment by abcoathup** [comment]
The timeout can be specified (though you reported that it appeared to be capped at 750 seconds)
>https://docs.zeppelinos.org/docs/cli_create.html
`--timeout <timeout>`  timeout in seconds for each blockchain transaction (defaults to 600s)

The following is the Proxy (as per the verified source code) which is what you should use to interact with the token:
https://etherscan.io/address/0x10a6a5ad6b3788a9deeccfd2a2eeed8333448844#contracts

Forum discussion: https://forum.zeppelin.solutions/t/transaction-was-not-mined-within750-seconds-please-make-sure-your-transaction-was-properly-sent/959

**Comment by abcoathup** [comment]
I assume the 750 second timeout is a 50 block timeout, potentially from one of the underlying tools. 

I hit this timeout when deploying a sample contract with a safe low gas price from https://ETHgas station.info though the gas market is volatile.

**Comment by spalladino** [comment]
Hey @itinance! The version of web3 we rely upon has these values hardcoded, and it's not possible to modify them unfortunately. The timeout parameter is being used in very few situations unfortunately - only those in which we do have direct control of the tx. I'm setting this issue on-hold until we find a solution in web3.

**Comment by itinance** [comment]
Hi @spalladino. When I was running into this issue it happens a whole day maybe due to some traffic jam on mainnet. Later it haven't occurred any more. So it had definitely something to do with this hardcoded timeout. 

Maybe we should reach out to the developers behind web3 and asking if PullRequest could be accepted to increase this timeout? I understand, that one might won't care about increasing such an timeout but in order to get full advantage out of ZeppelinOS even on such days with a "slow blockchain" due to traffic jam, it could be very helpful that "zos deploy" can wait until everything was finally mined to populate zos.-.json files with valid addresses.

**Comment by spalladino** [comment]
Hey @itinance! Web3 1.0 stable was released today, so we can now start pushing bugfixes to it, such as accepting a configurable timeout. We'll look into this during the upcoming days.

**Comment by spalladino** [comment]
Hey @itinance, we may have taken a bit more than originally planned, but we have reworked how web3 timeouts are handled in the [2.7 RC](https://forum.openzeppelin.com/t/openzeppelin-cli-2-7-rc-0-available/2133). Give it a try when you can!

**Comment by itinance** [comment]
Yes, @spalladino, I've already noticed your closed PR yesterday. Very good!!!! Thx!
