### ISSUE TITLE
Allow to specify a branch name for unpack command

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1103]
As a starter kit developer, I would like to test a new version of my kit before shipping it to all my users, so I don't accidentally push an incorrect version.

Right now, unpack always pulls code from the `stable` branch. We should support another parameter (either positional or named) that specifies a branch name (or just a git commit-ish) to pull, so a developer can test the unpack process _before_ promoting it to stable.

Edit: This would also help in downloading older versions if kits, if needed.

**Comment by ylv-io** [comment]
I'd rather go with commits so there will be no need to pollute branch space.

**Comment by spalladino** [comment]
Implemented in https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1190
