### ISSUE TITLE
Timeout not respected

### ISSUE THREAD

**Issue by miguelmota** [OpenZeppelin/openzeppelin-sdk#1132]
We tried deploying contracts for a client using zos push with `--timeout=1200` as specified in [docs](https://docs.zeppelinos.org/docs/cli_push.html) but according to the error logs the timeout expired at `750s`:

![2019-06-27 14 48 09 (1)](https://user-images.githubusercontent.com/168240/61557094-319fbd00-aa18-11e9-973a-b0f00efdbe31.jpg)

We were using `truffle-privatekey-provider` pointing to `https://mainnet.infura.io/v3/a6b85a49167f411b8c58834a16acf5ed` and zos  `2.2.2`

We eventually were able to sucessfully deploy the contracts by setting a high gas price and beating the timeout. The client contracts are [here](https://github.com/mpv-capitals/mpv-smart-contract) if you want to take a look.

Thanks

**Comment by abcoathup** [comment]
Unfortunately the 750 seconds is a web3 restriction.

> https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1065#issuecomment-512582118
> The version of web3 we rely upon has these values hardcoded, and it's not possible to modify them unfortunately. The timeout parameter is being used in very few situations unfortunately - only those in which we do have direct control of the tx. I'm setting this issue on-hold until we find a solution in web3.

**Comment by miguelmota** [comment]
Thanks for the info. Closing then.
