### ISSUE TITLE
Enhancement: Offer a complete networks.js file

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#1143]
Currently when we run `oz init` we are generated a basic `networks.js` config file. 
```
module.exports = {
  networks: {
    development: {
      protocol: 'http',
      host: 'localhost',
      port: 8545,
      gas: 5000000,
      gasPrice: 5e9,
      networkId: '*',
    },
  },
};
```

It might be nice if the initial `networks.js` was more detailed, at a minimum listing all the test networks and the main-net and demonstrating how to use hdwallet provider for deploying to other networks, (or whatever we might use as a provider).

**Comment by spalladino** [comment]
Closing in favor of #1182
