### ISSUE TITLE
Missing Example inputs for CLI

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#1144]
We are missing some example inputs from the CLI in version 2.5 that were present in 2.5-rc1. 

<img width="497" alt="Screen Shot 2019-07-22 at 12 55 03 PM" src="https://user-images.githubusercontent.com/1938013/61649722-09b29280-ac80-11e9-8688-5822ef688503.png">

<img width="466" alt="Screen Shot 2019-07-22 at 12 54 45 PM" src="https://user-images.githubusercontent.com/1938013/61649724-0a4b2900-ac80-11e9-9a88-0532ab200c51.png">

It's not a big deal, but it's nice to see the example shown, especially when it automatically loads the name of the folder.

The same thing for version: 

<img width="468" alt="Screen Shot 2019-07-22 at 12 53 44 PM" src="https://user-images.githubusercontent.com/1938013/61649775-1fc05300-ac80-11e9-8285-64a76055c2da.png">
<img width="470" alt="Screen Shot 2019-07-22 at 12 51 56 PM" src="https://user-images.githubusercontent.com/1938013/61649776-1fc05300-ac80-11e9-9c27-aa5ea0537de2.png">

**Comment by spalladino** [comment]
This is currently working properly for me. Are you sure it isn't that you are missing a `package.json` on the folder?

**Comment by crazyrabbitLTC** [comment]
The problem seems to have disappeared for me, I'm not sure if it was related to a `package.json` or not.
