### ISSUE TITLE
`Loggy.noSpin` has confusing name and to verbose

### ISSUE THREAD

**Issue by ylv-io** [OpenZeppelin/openzeppelin-sdk#1147]
Method name `noSpin` is confusing because it is essentially just `console.log`.
`Loggy.noSpin(__filename, 'getOptions', 'get-options', 'Using session with ${describe(fields)}');`

Log methods calls are too verbose and has a high maintain cost. You have manually to edit all the method names if they change. Method name can be extracted automatically.

**Comment by spalladino** [comment]
Closing in favor of #1315
