### ISSUE TITLE
Call command does not prompt for arguments on autogenerated getters for arrays

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#1151]
When calling a public method that takes arguments, such as an array, It would be nice if, like `send-tx` the cli prompted us for arguments. 

Currently (v2.5) it does not: 

<img width="500" alt="Screen Shot 2019-07-23 at 1 05 22 PM" src="https://user-images.githubusercontent.com/1938013/61732021-b1949280-ad4a-11e9-891b-e1430e4c1eec.png">

If however I try to send in an argument (the number 1 in this case, for an array) I get this error. Perhaps I am doing it wrong, but the UX perhaps could be improved. 

<img width="536" alt="Screen Shot 2019-07-23 at 1 07 15 PM" src="https://user-images.githubusercontent.com/1938013/61732124-ebfe2f80-ad4a-11e9-9f92-25d3758bc81a.png">

**Comment by spalladino** [comment]
Can you share the contract you used for this?
Also, was it v2.5.0, or v2.5.1?

**Comment by crazyrabbitLTC** [comment]
This was for version v2.5.0, I'll test it as soon as I can on v2.5.1. 

The contract is: 

```
pragma solidity ^0.5.0;
contract Name {
        string public name;
        string[] public names;
function setName(string memory _name) public {
        names.push(_name);
        name = _name;
}
}
```

**Comment by crazyrabbitLTC** [comment]
It seems to also not work on version v2.5.1.
<img width="537" alt="Screen Shot 2019-07-23 at 5 09 47 PM" src="https://user-images.githubusercontent.com/1938013/61747817-b66a3e00-ad6c-11e9-89c7-04fa09f34718.png">

**Comment by spalladino** [comment]
Working fine on 2.6.1
