### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by pcowgill** [OpenZeppelin/openzeppelin-sdk#1157]
This link `xref:writing_contracts.adoc#modifying-your-contracts[remove or change the type of a contract state variable]` is broken in [this file](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/docs/modules/ROOT/pages/first.adoc).

<img width="927" alt="Screenshot 2019-07-25 12 49 31" src="https://user-images.githubusercontent.com/2731712/61896620-fa7b5100-aeda-11e9-9712-76b047642366.png">

**Comment by pcowgill** [comment]
@frangio If you have any instructions on the best way to modify the new `.adoc` files, I'd be happy to fix this!

**Comment by frangio** [comment]
@pcowgill Oh good catch. I renamed the files from underscores to dashes and forgot to fix the links to those files. :sweat_smile: 

You can just edit the file that you linked to. I can't think of anything else that you should keep in mind. Let me know if you had any particular concern.

**Comment by pcowgill** [comment]
@frangio Haha oops, yes these files can be edited like any other type of files. I could have sworn the edit button wasn't appearing in the GitHub UI. My mistake. Thanks!

**Comment by pcowgill** [comment]
@frangio Opened a PR for this https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1170
