### ISSUE TITLE
web3@1.0.0-beta.37 can change to web3@1.2 now in the docs

### ISSUE THREAD

**Issue by pcowgill** [OpenZeppelin/openzeppelin-sdk#1158]
`web3@1.0.0-beta.37` can change to `web3@1.2` now in the [docs](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/docs/modules/ROOT/pages/interacting.adoc)

(I opened this as an issue rather than making the change in a PR myself since I'm not sure of the best way to make changes to .adoc files.)

[1.x blog post](https://medium.com/@samuel_91690/1-0-release-web3-js-ddd23d3c8f62)
[web3.js releases](https://github.com/ethereum/web3.js/releases)

**Comment by spalladino** [comment]
Good catch! We'll be releasing a new version with 1.2 real soon, and then update :-)

**Comment by pcowgill** [comment]
> Good catch! We'll be releasing a new version with 1.2 real soon, and then update :-)

@spalladino I see [the change was released](https://github.com/OpenZeppelin/openzeppelin-sdk/releases/tag/v2.5.2), so I opened a PR for this https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1171

I'm not sure why the `.adoc` files were confusing me before - they're straightforward to edit from within the GitHub UI.

**Comment by spalladino** [comment]
Closing issue as fixed
