### ISSUE TITLE
Update the babel config docs now that Truffle is an optional dependency

### ISSUE THREAD

**Issue by pcowgill** [OpenZeppelin/openzeppelin-sdk#1159]
The [Babel config section](https://docs.openzeppelin.com/sdk/2.5/faq#how-do-i-use-es6-javascript-syntax-in-my-tests) should take into account the presence of [the new `networks.js` config file](https://docs.openzeppelin.com/sdk/2.5/new-2.4#standalone-cli) that is the default name of the file created when creating a new project with `@openzeppelin/cli`.

**Comment by spalladino** [comment]
Putting this one on hold until we ship a process for testing outside truffle.

**Comment by pcowgill** [comment]
I'll note that now that I understand that the scope of `networks.js` is smaller than `truffle-config.js`, this change most likely wouldn't affect the `networks.js` file at all.

**Comment by spalladino** [comment]
@nventuro can you tackle this as part as the documentation revamp?

**Comment by nventuro** [comment]
Testing documentation now lives on the [Test Environment docs](docs.openzeppelin.com/test-environment), which are Babel-agnostic. Closing this issue.

**Comment by pcowgill** [comment]
@nventuro Thanks!
