### ISSUE TITLE
`npx oz verify` Error while trying to verify contract: Fail - Unable to verify

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1183]
Unable to verify using OpenZeppelin SDK.
`npx oz verify` results in the following error: 
```
Error while trying to verify contract: Fail - Unable to verify
```
OpenZeppelin CLI Version 2.5.2
```console
$ npx oz --version
2.5.2
```

## Verify to Etherscan on Ropsten
```console
$ npx oz verify --verbose
? Pick a contract Counter
? Pick a network ropsten
? Was the optimizer enabled when you compiled your contracts? No
? Select an endpoint etherscan
? Provide an etherscan API KEY ZZZZMYAPIKEYZZZZ
[2019-08-07T00:21:02.274Z@NetworkController.js#verifyAndPublishContract] <started> Verifying and publishing contract source code of Counter on etherscan (this usually takes under 30 seconds)
[2019-08-07T00:21:20.856Z@ErrorHandler.js#call] <started> Error: Error while trying to verify contract: Fail - Unable to verify
    at /mnt/c/Users/andre/Documents/projects/forum/verify/node_modules/@openzeppelin/cli/lib/models/Verifier.js:112:19
    at Generator.throw (<anonymous>)
    at rejected (/mnt/c/Users/andre/Documents/projects/forum/verify/node_modules/@openzeppelin/cli/lib/models/Verifier.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
## Contract
```solidity
pragma solidity ^0.5.0;

contract Counter {
  uint256 public value;

  function increase() public {
    value++;
  }
}
```
## ropsten.json
```js
  "proxies": {
    "verify/Counter": [
      {
        "address": "0x5898404794Bd664794d37dC242E6DAeEd3A7c56f",
        "version": "1.0.0",
        "implementation": "0x4faA78654cF9b5a338e9C80feC0D6846d240560A",
        "admin": "0xB2B810A79fb1D9c2ea031989e0a7ED6dAC23bCb2",
        "kind": "Upgradeable"
      }
    ]
  },
```

**Comment by genecyber** [comment]
This is a non starter, many places require contract source verification. I’ve got 2 advanced erc20 contracts deployed that I can’t verify and it’s impacting my ability to utilize them. Please advise

**Comment by abcoathup** [comment]
Explicitly setting optimizer off in compile allows cli verify on Etherscan.  
Not explicitly setting optimizer off in compile and the cli fails to verify on Etherscan.  

It is unclear what optimize settings are used by default as the optimize settings are blank in the contract json and the project json.
```
    "optimizer": {},
```

As an aside, OpenZeppelin SDK uses EVM version `constantinople` by default, whilst current default EVM version is `petersburg` 
(Though the documentation states there is no difference https://solidity.readthedocs.io/en/latest/using-the-compiler.html#target-options)
Etherscan verify API doesn't allow EVM version to be specified


```console
$ npx oz compile --optimizer off --optimizer-runs 200
✓ Compiled contracts with solc 0.5.11 (commit.c082d0b4)

$ npx oz create
Nothing to compile, all contracts are up to date.
? Pick a contract to instantiate Counter
? Pick a network ropsten
✓ Contract Counter deployed
All contracts have been deployed
? Do you want to call a function on the instance after creating it? No
✓ Setting everything up to create contract instances
✓ Instance created at 0x0fA470cb9B31e2C788B82e77e87DcB9366BdBE74
0x0fA470cb9B31e2C788B82e77e87DcB9366BdBE74

$ npx oz verify
? Pick a contract Counter
? Pick a network ropsten
? Was the optimizer enabled when you compiled your contracts? No
? Select an endpoint etherscan
? Provide an etherscan API KEY XXXXXXXXXXXXXXXXXXX
✓ Contract source code of Counter verified and published successfully. You can check it here: 
https://ropsten.etherscan.io/address/0x7d75771d9fCb02930Bde01c0E402B6291899750D#code
```
## build/contracts/Counter.json excerpt
```json
  "bytecode": "0x6080604052348015600f57600080fd5b5060a98061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80633fa4f245146037578063e8927fbc146053575b600080fd5b603d605b565b6040518082815260200191505060405180910390f35b60596061565b005b60005481565b600080815480929190600101919050555056fea265627a7a723158201b6f4b2889da19b0998110a92509da704baf2daf55c2f6626a1a92b6bc13265c64736f6c634300050b0032",
  "deployedBytecode": "0x6080604052348015600f57600080fd5b506004361060325760003560e01c80633fa4f245146037578063e8927fbc146053575b600080fd5b603d605b565b6040518082815260200191505060405180910390f35b60596061565b005b60005481565b600080815480929190600101919050555056fea265627a7a723158201b6f4b2889da19b0998110a92509da704baf2daf55c2f6626a1a92b6bc13265c64736f6c634300050b0032",
  "compiler": {
    "name": "solc",
    "version": "0.5.11+commit.c082d0b4.Emscripten.clang",
    "optimizer": {
      "enabled": false,
      "runs": 200
    },
    "evmVersion": "constantinople"
  }
```

Just explicitly setting the optimizer off also works.
```console
npx oz compile --optimizer off
```
https://ropsten.etherscan.io/address/0x44711136e790c368E440e3172Ac00084c710797a#code

Not explicity setting the optimizer off (assume it is enabled) fails to verify

```console
$ npx oz compile
✓ Compiled contracts with solc 0.5.11 (commit.c082d0b4)

$ npx oz create
Nothing to compile, all contracts are up to date.
? Pick a contract to instantiate Counter
? Pick a network ropsten
✓ Contract Counter deployed
All contracts have been deployed
? Do you want to call a function on the instance after creating it? No
✓ Setting everything up to create contract instances
✓ Instance created at 0x5F7134A57737Ba46A48bc24Ff447424b084Dcb24
0x5F7134A57737Ba46A48bc24Ff447424b084Dcb24
```
## build/contracts/Counter.json excerpt
```json
  "bytecode": "0x60806040523480156100115760006000fd5b50610017565b60b7806100256000396000f3fe608060405234801560105760006000fd5b506004361060365760003560e01c80633fa4f24514603c578063e8927fbc146058576036565b60006000fd5b60426060565b6040518082815260200191505060405180910390f35b605e6069565b005b60006000505481565b600060008181505480929190600101919050909055505b56fea265627a7a72315820de26d85a176277242d9d3f0b76d118dfd4d8b63ccbb75bf491b1db0c4fba21c964736f6c634300050b0032",
  "deployedBytecode": "0x608060405234801560105760006000fd5b506004361060365760003560e01c80633fa4f24514603c578063e8927fbc146058576036565b60006000fd5b60426060565b6040518082815260200191505060405180910390f35b605e6069565b005b60006000505481565b600060008181505480929190600101919050909055505b56fea265627a7a72315820de26d85a176277242d9d3f0b76d118dfd4d8b63ccbb75bf491b1db0c4fba21c964736f6c634300050b0032",
  "compiler": {
    "name": "solc",
    "version": "0.5.11+commit.c082d0b4.Emscripten.clang",
    "optimizer": {},
    "evmVersion": "constantinople"
  }
```
Fails to verify with the CLI
https://ropsten.etherscan.io/address/0x746f1A3470214e545eB4d0249f03Ed295E2999de#code

**Comment by abcoathup** [comment]
Hi @melnikaite 

Currently the OpenZeppelin SDK uses EVM version `constantinople`

Shouldn't the OpenZeppelin SDK use the EVM version based on the default for the compiler version:
`byzantium` prior to 0.5.5 https://solidity.readthedocs.io/en/v0.5.4/using-the-compiler.html#target-options
`petersburg` from 0.5.5: https://solidity.readthedocs.io/en/v0.5.5/using-the-compiler.html#target-options

**Comment by melnikaite** [comment]
Have a look please at #1208 
I implemented detecting default version according to compiler rules

**Comment by melnikaite** [comment]
Hi @genecyber 

I manage to verify both

**ProxyAdmin** 
 https://etherscan.io/address/0x6d5c4d5ad83f8a2bf0347cbe5d550c65e6ecf39c#code
**AdminUpgradeabilityProxy** 
 https://etherscan.io/address/0x5f737cb5cc40d0d4213e2fffff7a05e792816767#code

using compiler 0.5.3 EVM byzantium no optimization

**Comment by shanefontaine** [comment]
For anyone trying to manually verify the problem with version 2.5.3 of OpenZeppelin (September 2019 ), I was able to verify `InitializableAdminUpgradeabilityProxy.sol` with the following parameters:
* Compiler version: v0.5.3+commit.10d17f24
* Optimization: None
* EVM Version: Default

I used [truffle-flattener](https://www.npmjs.com/package/truffle-flattener) to flatten the contracts directly in my `node_modules`.

You can find the verified contract [here](https://etherscan.io/address/0x02eefd8fd2debc75c52ef1479e56caeaa049ecc7#code).

**Comment by chekan-o** [comment]
Hi,

I'm using openzepplin version 2.6.0 and can't verify Proxy contract. 
Which file and settings should I use?

Thanks

**Comment by chekan-o** [comment]
I've made one more attempt with solidity version 0.5.3 EvmVersion set to `constantinople` and finally it worked.

**Comment by abcoathup** [comment]
Hi @chekan-o,
I wrote up the process for anyone trying to do this:
https://forum.openzeppelin.com/t/verify-proxy-contract/1989
