### ISSUE TITLE
Countract deployed message duplicated while using `oz create`

### ISSUE THREAD

**Issue by ylv-io** [OpenZeppelin/openzeppelin-sdk#1189]
![image](https://user-images.githubusercontent.com/3285000/63109540-c4853600-bf89-11e9-9050-26c3fb3ecaaf.png)

**Comment by melnikaite** [comment]
Unfortunately I didn't manage to reproduce it. I see just one one message.

Could you please share your projects?

**Comment by spalladino** [comment]
Closing. @ylv-io please reopen if still happens!
