### ISSUE TITLE
Error: EACCES: permission denied '.../keccak/.node-gyp'

### ISSUE THREAD

**Issue by vbaranov** [OpenZeppelin/openzeppelin-sdk#1199]
`
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@openzeppelin/cli/node_modules/keccak/.node-gyp'
`
```
viktor$ node -v
v10.16.3
viktor$ npm -v
6.9.0
```

on running `sudo npm install --global @openzeppelin/cli`

**Comment by vbaranov** [comment]
For those who will be faced with the same issue add `--unsafe-perm` flag to installation command:
`sudo npm install --unsafe-perm --global @openzeppelin/cli`

It would be awesome to have this note somewhere in `README`

**Comment by abcoathup** [comment]
Hi @vbaranov 

As I understand it you should avoid using `sudo` with `npm`.

One way to resolve EACCES permission errors is to use a node version manager.
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

I use nvm.  I also tend to install packages locally rather globally.
https://forum.openzeppelin.com/t/installing-packages-locally-rather-than-globally-npx/663

**Comment by vbaranov** [comment]
@abcoathup Sure thing. I did it with `sudo`. And it didn't work with `sudo` without that flag. This is why I created the issue.

**Comment by jcarpanelli** [comment]
Hi there @vbaranov! This is not a problem with the `sdk` itself, but an access/privileges problem with your global `node_modules` folder. This error might appear for some dependencies (not for all of them), dependening on, for instance, whether they have to compile c/c++ code on your system or not (btw, I've just tested this downloading the LTS version of node.js and didn't face this problem).

Regarding https://github.com/OpenZeppelin/openzeppelin-sdk/pulls/1200, I'm skeptical about adding the `--unsafe-perm` flag, as this is not a final solution but a patch. 
We'll dig more deeply into this so we can provide more info in the docsite on how to get rid of the error by checking and fixing the permissions issue.

**Comment by vbaranov** [comment]
@jcarpanelli thanks for the thorough clarification. I saw, that not only me had the same problem on OpenZeppelin workshop in EthBerlin. And, thus, I thought this workaround can be helpful for others who faced the same issue. But feel free to close my PR if you think this is not a final solution.
