### ISSUE TITLE
Add Contract instance by JSON and Address

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#1204]
It would be very nice if we could use features like `oz call` on contracts that we haven't ourselves deploy. 

Example: 

Contract A deploys contract B. 

Using the CLI . I can `oz call` or `oz send-tx` on any function on contract A. However even though contract A deploys contract B, I can not `oz send-tx` or `oz call` anything on Contract B. 

It would be nice to be able to ADD contract B via it's address as we have the code available (Contract A knows it's ABI to be able to deploy it).

**Comment by spalladino** [comment]
Closing in favor of #1264
