### ISSUE TITLE
Value is not stored in storage with TestHelper

### ISSUE THREAD

**Issue by toshiboy86** [OpenZeppelin/openzeppelin-sdk#1207]
Implementation of storing data in storage never work with running `truffle test`, although the same data process in `initialize` function works and also manually running `oz` code in command line with the same contract works successfully.
No error showed up.

Here is the sample code.

testToken.sol
```
pragma solidity ^0.5.0;
import "@openzeppelin/contracts-ethereum-package/contracts/token/ERC721/ERC721Full.sol";
import "@openzeppelin/upgrades/contracts/Initializable.sol";

contract testToken is Initializable, ERC721Full { 
    mapping(uint256 => mapping(bytes32 => string)) public _stringStorage;

    function initialize(string memory _tokenName) public {
        tokenName = _tokenName;
        _stringStorage[1][keccak256("test")] = "new1";
    }

    function setTest() public {
        _stringStorage[1][keccak256("test")] = "new2";
    }

    function getTest() public view returns(string memory) {
        return _stringStorage[1][keccak256("test")];
    }

　function getStaticTest() public view returns(string memory) {
        return "StaticTest";
    }

}
```

test.js
```
const { TestHelper } = require('@openzeppelin/cli');
const { Contracts, ZWeb3 } = require('@openzeppelin/upgrades');
ZWeb3.initialize(web3.currentProvider);
const testToken = Contracts.getFromLocal('testToken');

contract('ABNMarket deploy', function () {
  let proxy;

  beforeEach(async function () {
    this.project = await TestHelper();
    proxy = await this.project.createProxy(testToken, {
      initMethod: "initialize",
      initArgs: ["TEST"]
    });
  })

  it('mint', async function () {
    await proxy.methods.setTest("abntoken").call();
    let res = await proxy.methods.getTest().call();
    console.log(res); // returns "new1", I expected "new2"
  });
});
```

After running `await proxy.methods.setTest("abntoken").call();`, 
the value `res` should be `new2` but it is actually `new1`, regardless of some attempts.
(`getStaticTest` function works properly, which indicates static value is successfully returned)

Version information is as follows:
```
Truffle v5.0.30 (core: 5.0.30)
Solidity v0.5.0 (solc-js)
Node v11.14.0
Web3.js v^1.2.0

"@openzeppelin/cli": "^2.5.2",
"@openzeppelin/contracts-ethereum-package": "^2.2.1",
"@openzeppelin/upgrades": "^2.5.2",
```

Any help and comments are appreciated.

**Comment by toshiboy86** [comment]
I've just found the answer by myself. 
We have to use `send` method with a particular EOA address  instead of `call` method .

`await proxy.methods.setTest("abntoken").send({from: YOUR_EOA});`

Replacing the code above works successfully.

**Comment by abcoathup** [comment]
Hi @toshiboy86 I was reproducing your issue and spotted that you were doing a `call` when I saw that you had already found it.  Great that you were able to resolve.

For support questions you can ask in the Community Forum: https://forum.openzeppelin.com/
