### ISSUE TITLE
Documentation: Broken link to UML diagram on Contracts Architecture page

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1218]
The [Contracts Architecture](https://docs.openzeppelin.com/sdk/2.5/architecture) page in the documentation in the [Overview section](https://docs.openzeppelin.com/sdk/2.5/architecture#overview) has a broken link to a UML diagram.  
```
[[overview]]
== Overview

The following diagram illustrates the interface of the contracts of published Ethereum Packages:

image:/img/zos2.png[OpenZeppelin SDK 2.x UML]
```
I assume that the diagram is: https://github.com/OpenZeppelin/openzeppelin-sdk/blob/release/2.4/packages/docs/docs/website/static/img/zos2.png

The diagram should be placed here: 
https://github.com/OpenZeppelin/openzeppelin-sdk/tree/master/packages/docs/modules/ROOT/assets/images

And referred to as:
`image:/img/zos2.png[OpenZeppelin SDK 2.x UML]`

First reported in the forum: https://forum.openzeppelin.com/t/openzepppelin-sdk-architecture-diagram/1286

**Comment by frangio** [comment]
Thanks @abcoathup! Fixed it and pushed it for deployment.
