### ISSUE TITLE
send-tx and call commands potentially list wrong contract functions

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#1222]
In the particular case where the user has an instance that is not up to date to the locally compiled code, the listed functions presented when running `oz call` and `oz send-tx` will be wrong.
A possible solution would be saving the ABI of the deployed contract in the network file, within the instance info.

**Comment by spalladino** [comment]
@frangio given you're reviewing the structure of the `network.js` file for regular deploys, you may want to take this issue into consideration.

**Comment by spalladino** [comment]
Closing in favour of #1313
