### ISSUE TITLE
Documentation: Formatting of openzeppelin|oz in SDK API CLI doc

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1242]
openzeppelin|oz is not formatted correctly in SDK API CLI documentation:

> https://docs.openzeppelin.com/sdk/2.5/api/cli
> [[openzeppelin|oz]] == openzeppelin|oz

I don't know if the | causes an issue in the documentation generation: https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/cli/src/bin/program.ts

**Comment by frangio** [comment]
Good catch! Thank you. I fixed it in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/53bd469edd1dcee0e7b68a15a78b335762e5bf70.
