### ISSUE TITLE
Ownable contract owner is always the 0 address

### ISSUE THREAD

**Issue by Chrissie** [OpenZeppelin/openzeppelin-sdk#1270]
When using Ownable, the owner of the contract is always the null address.

```
pragma solidity ^0.5.0;

import "@openzeppelin/contracts/ownership/Ownable.sol";

contract Tester is Ownable {
    function sayHi() public view returns(string memory) {
        return "hi";
    }
}
```
Then deploy it to my local blockchain with openzeppelin create. Calling openzeppelin call on the owner function will result in 0x0000000000000000000000000000000000000000. I have no clue how to proceed.

I also posted this issue on the forums:
https://forum.openzeppelin.com/t/ownable-contract-owner-is-always-the-0-address

**Comment by abcoathup** [comment]
Hi @Chrissie,

I have answered in the forum: 
https://forum.openzeppelin.com/t/ownable-contract-owner-is-always-the-0-address/1646/2

I suggest this issue can be closed and any further questions can be picked up in the forum.

**Comment by abcoathup** [comment]
Closing as solved specific issue in the forum.  

Documentation could be improved to advise that we need to use `@openzeppelin/contracts-ethereum-package` with upgradeable contracts.
