### ISSUE TITLE
Clean up root READMEs

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1272]
We currently have:

- TERMINOLOGY.md, which is mostly outdated
- README.md, with deprecated instructions on how to set up the project locally
- CONTRIBUTING.md, with deprecated instructions on how to set up the project locally
- HACKING.md, with updated instructions on that setup

I propose:

- Delete TERMINOLOGY.md
- Place all dev env setup instructions in a single place (I'd suggest the README) and remove from other files (this would imply deleting HACKING as well)

Thoughts? @frangio @abcoathup

**Comment by frangio** [comment]
I agree on deleting the terminology document.

I think dev env setup should go in the contributing guide rather than in the README. I would keep the latter focused on usage.

**Comment by spalladino** [comment]
> I think dev env setup should go in the contributing guide rather than in the README. 

Ok for me, as long as we keep a reference to it on the README explaining that the dev setup instructions are there.

**Comment by abcoathup** [comment]
I like README for use and CONTRIBUTING for process and environment setup.

**Comment by spalladino** [comment]
It's settled then. @abcoathup do you want to tackle this one then?
