### ISSUE TITLE
Automate conversion of vanilla contracts to upgradeable contracts

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1300]
Create a new project in the monorepo that accepts a set of sources and build artifacts (this is, including the solc-generated AST) and creates corresponding contracts which are upgradeable (ie have initializers instead of constructors, among other things).

- [x] Build a function that, given original source and AST, can inject changes on the original source via AST-based instructions. Check existing linters who already do this. Note that we don't need to support any arbitrary change, only the ones required for implementing the following items.
- [ ] Build a function that, given a contract's AST, adds a storage gap at its end, so that total storage slots amount to 100.
- [x] Build a function that, given a contract's AST (with no inheritance), changes its constructor to an initializer function. Discuss whether we should still have a base Initializer class, or we should embed all initialization logic (ie the initialized flag) in the contract.
- [x] Build a function that, given a contract's AST (with no inheritance), scans all variable declarations with initial values, and moves those to the initializer function (creating the initializer if it does not exist).
- [x] Build a function that, given a contract's AST and all its base contracts ASTs, applies all the transformations listed above recursively. Consider special cases around constructors and inheritance: calling super in the ctor, calling the constructor by contract name in the declaration of the function, or even in the contract declaration. See the ANTLR grammar to ensure we capture all scenarios. Also consider whether we should condense all initializer code in the most derived contract, or we should change all base contracts having one initializer for each of them.
- [x] Build a function that, given a set of artifacts and a contract by name, collects the contract's AST and all of its ancestors, creating the input required for the function above. Note that this function may already exist in upgrades.js.

**Comment by ylv-io** [comment]
Linters
* [Solhint](https://github.com/protofire/solhint)
* [Solium](https://github.com/duaraghav8/Ethlint)
Good source of reference code and algorithms.

**Comment by ylv-io** [comment]
[A Solidity parser for JS built on top of a robust ANTLR4 grammar](https://github.com/federicobond/solidity-parser-antlr)

**Comment by spalladino** [comment]
@ylv-io note that fede's parser yields a different AST than that of solc. If we do use it, we should consider how difficult it would be to keep the syntax definition up to date, and also time it vs solc.

**Comment by spalladino** [comment]
You may also want to check out the [experiments from labs](https://github.com/OpenZeppelin/openzeppelin-labs/tree/master/initializer_with_sol_editing) on this from last year. There is also a link to Solium's autofix that could come in handy.

**Comment by ylv-io** [comment]
@spalladino how do even know that use different AST? And what kind of AST it is? Can't find any docs on that.

**Comment by spalladino** [comment]
@ylv-io you won't find docs on either one. I'd suggest you just run the ANTLR parser and compare it to the AST generated in the solc build artifact, you'll see they use different formats right away.

**Comment by ylv-io** [comment]
Docs on artifacts AST.

> There is a grammar.txt in the solidity repo which I hadn't seen before, though I'm not sure whether it's actually used or just documentation https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt 

> And the AST.h file may be of help as well https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/AST.h#L378 (e

by @spalladino

**Comment by ylv-io** [comment]
[prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity) does automatic Solidity code transformations.
