### ISSUE TITLE
Design automated conversion to upgradeable contracts in the CLI

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1301]
Given #1300, we need the CLI to automatically transform the contracts and make them available to the user somehow. A first step would be to design how this should work, tackling the following questions:

1. How should we distinguish a vanilla contract that will be deployed regularly, from a vanilla contract that needs to be converted to be deployed as an upgradeable one? Should this be hinted when writing the contracts (by adding a marker interface or magic comment, for example), when compiling or adding, or when deploying?
2. Where should the transformed sources be stored? We can keep them within the build folder, so the CLI picks them up when it needs to verify an upgradeable instance. Or in the contracts folder itself, so the user has direct access to them. In the latter, we will probably need to rename them to avoid name clashes.
3. How will we allow users to create upgradeable instances from Solidity? Should we stick to the App/Package/Provider pattern? Or look into alternatives?

Roughly, the integration should take the following steps. As part of this issue, we should review this list and identify if there are any missing steps, or if any of them may cause any problems:

1- Compile all contracts
2- Identify those to be converted into upgradeable contracts
3- Convert them
4- Compile them as well
5- Change the create command so it can handle both upgradeable and vanilla deploys
6- Review all commands to see how this distinction impacts them

Note that this issue also involves figuring out regular deploys. We may want to finish that issue first before going with this one.

**Comment by frangio** [comment]
1. The decision is based on the `--kind` flag of `oz deploy`. Proxy deployments would go through the transpiler. Some contracts may not need to go through the transpiler. For that, see https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1493.

2. Transformed sources are stored in `contracts/__upgradeable__` in a directory structure that simulates the existing directory structure under `contracts`, plus directories for dependencies.

3. See #1488.
