### ISSUE TITLE
Make compiler config interactive

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-sdk#1302]
`oz compile` uses the latest compiler version by default, unless one is explicitly passed, or a config file (`networks.js`) exists.

Instead, when running it with no supplied config, `compile` should instead:
 * prompt the user to select a compiler version (perhaps with one being recommended by us?)
 * save the selected configuration to the filesystem, to ensure reproducibility

**Comment by spalladino** [comment]
Not sure I agree. I'd rather have `compile` just outright compile, as in most cases the most reasonable choice for the user is just picking the latest compiler (that satisfies all pragmas), and avoid bothering the user with questions.

**Comment by nventuro** [comment]
An issue with that approach is that stuff may suddenly stop working once a new compiler comes out, and it might very hard to realize that this is the underlying cause. 

Though I don't expect Solidity to break semver at the language level, other bits may change, including options such as default target EVM may change (leading to issues on sidechains), the format of the artifacts (which may cause issues with tools). The fact that the generated bytecode itself will be different might be undesirable, such as when dealing with singleton schemes, or using `create2` in factories.

Still, that is argument for reproducibility, not interactiveness. What do you think about that part of the suggestion?

**Comment by spalladino** [comment]
> An issue with that approach is that stuff may suddenly stop working once a new compiler comes out, and it might very hard to realize that this is the underlying cause.

That's not the case. On the first run, `oz compile` writes to `project.json` the compiler settings used, and those are used for all subsequent compilations.

**Comment by nventuro** [comment]
Ah, I may have stumbled into a bug then. If `oz compile` is run but no project was initialized, the `.openzeppelin` directory will be created, but left empty: `compile` will not store the compiler settings anywhere.

**Comment by spalladino** [comment]
Closed in favor of #1303
