### ISSUE TITLE
Do not report push usages in CLI telemetry if called from within another contract

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1305]
Whenever an implementation contract is pushed, potentially as part of a `create` or `upgrade` command run, the CLI telemetry reports as if the `push` command had been called manually by the user. This makes it ~difficult~ impossible to identify how many times `push` was actually called.

**Comment by frangio** [comment]
This has already been fixed.

https://github.com/OpenZeppelin/openzeppelin-sdk/blob/ee7497c43c6d3da01ca4f6721877fe411b091fe1/packages/cli/src/commands/push.ts#L86-L87
