### ISSUE TITLE
Check for upgrade issues prior to deploying logic contract

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1311]
If there is an upgrade issue (e.g. new variable being inserted not at the end of the contract) there should be a way to check for these issues prior to deploying a logic contract.

When running `oz upgrade` it reports an issue and deploys the logic contract before there is an opportunity for the user to cancel and fix the issue:

`oz check` doesn't appear to report upgrade issues such as this one.

```
$ oz upgrade
? Pick a network development
Nothing to compile, all contracts are up to date.
- New variable 'uint256 _b' was inserted in contract Example in contracts/Example.sol:1. You should only add new variables at the end of your contract.
See https://docs.openzeppelin.com/sdk/2.5/writing-contracts#modifying-your-contracts for more info.
✓ Contract Example deployed
All contracts have been deployed
? Which instances would you like to upgrade? (Use arrow keys)
❯ All instances
  Choose by name
  Choose by address                     
``` 

Either `oz check` could include warnings for upgrade issues (if possible) or `oz create` could prompt the user if they want to continue once a warning is detected, prior to the deployment of a logic contract

**Comment by abcoathup** [comment]
Raised by a community member on the community forum: https://forum.openzeppelin.com/t/check-that-upgraded-contract-doesnt-violate-storagediff/1913

**Comment by spalladino** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1382
