### ISSUE TITLE
Commands could reject invalid addesses early

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-sdk#1341]
web3 provides [web3.utils.isAddress](https://web3js.readthedocs.io/en/v1.2.0/web3-utils.html#isaddress), which checks offline if a string is a valid address. We should use this in commands that prompt for an address, like `balance`, to either not progress until a valid one is entered or fail early.

**Comment by spalladino** [comment]
Closing as duplicate of https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1069
