### ISSUE TITLE
Command `create` bypasses contract validations

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#1348]
Contracts are validated to ensure they are upgradeable (eg by checking they have no ctors) at `push` time. If they fail the validation, the push command fails. However, if the contract is never `push`ed manually, but is handled instead automatically during a `create`, then the warnings will be displayed **but the contract will be pushed and created anyway**.

We should halt the `create` process if a validation error is thrown.

**Comment by frangio** [comment]
Is it just a matter of removing this line?

https://github.com/OpenZeppelin/openzeppelin-sdk/blob/62e1bca809f6a3a697a39130a899d7080e2ad5cd/packages/cli/src/commands/create.ts#L65

**Comment by spalladino** [comment]
That would certainly halt the deploy process, but I'd like to know what other consequences there are when removing that line.
