### ISSUE TITLE
Compilation when a project isn't initialized

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-sdk#1357]
In a directory with a contract at `contracts/Foo.sol`, `oz compile` says "No contracts found to compile". It only finds the contract if there is an `.openzeppelin` directory or a `package.json` file.

We should make it so that `oz compile` works when neither of these are present, so that usage is as simple as creating a `contracts` directory and putting source files in it.

**Comment by nventuro** [comment]
Superceded by https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1378 (which has a more detailed explanation).
