### ISSUE TITLE
Use the complete lodash package

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-sdk#1401]
Our packages currently use the single-function lodash packages such as `lodash.flatten`. I guess the reason is to avoid bringing the entire `lodash` package for stuff that we won't use. Counter-intuitively, though, this ends up being worse, because we have dependencies such as `inquirer` that depend on `lodash` themselves. As a result, the user ends up installing lodash along with all of the single-function packages. To put that in numbers, lodash itself is 5MB, and the small packages that we use add up to 2MB.

**Comment by spalladino** [comment]
For reference: https://github.com/OpenZeppelin/openzeppelin-sdk/pull/555
