### ISSUE TITLE
Deploy solidity libraries as evm packages instead of linking them at bytecode level

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#144]
Currently, solidity libraries are linked at bytecode level when a contract is compiled. Encouraging users to work with on-chain libraries we may want to treat Solidity libraries as on-chain libraries deploying them and fixing consumer contracts to use it as an on-chain dependency.

**Comment by spalladino** [comment]
Closing in favour of #653
