### ISSUE TITLE
"Proxy at address" error can be updated to reflect new non-upgradeable contract support

### ISSUE THREAD

**Issue by nopslip** [OpenZeppelin/openzeppelin-sdk#1479]
In testing cli:  `2.8.0-rc.2` I noticed if you try to `send-tx` to a contract that doesn't exist you get error message about Proxy not found.  With support the new support for non-upgradeable contracts this could be changed to something like, `Proxy or contract at address...`

` npx oz send-tx --to 0x9C5Dd70D98e9B321217e8232235e25E64E78C59 --value 1000000000000000000 --method supplyEthToCompound` 
Results in: 
`Proxy at address 0x9C5Dd70D98e9B321217e8232235e25E64E78C595 not found.`

**Comment by abcoathup** [comment]
Hi @nopslip !  I’m sorry that you had this issue.  

We have been able to reproduce this issue by following these steps:
Send a transaction using `oz send-tx` to an unknown contract specifying any method name
```javascript
$ npx oz send-tx --to 0x0000000000000000000000000000000000000000 --network development --method doStuff
Proxy at address 0x0000000000000000000000000000000000000000 not found.
```
Thanks so much for reporting it! The project owner will review and triage this issue during the next week.  

Thank you for trying out regular deploys.  Please let us know if you find any other issues in the release candidate.
