### ISSUE TITLE
`Contract undefined not found` with `npx oz deploy` of `@openzeppelin/contracts-ethereum-package/StandaloneERC20`

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#1481]
Deploying `@openzeppelin/contracts-ethereum-package` with OpenZeppelin CLI 2.8 RC2 gives error `Contract undefined not found` for both a development network and to a public testnet.

Works with OpenZeppelin CLI 2.71 using `oz create`.

node `v10.19.0`
npm `6.13.7`
oz `2.8.0-rc.2`
os: Windows 10 WSL

## Setup
```
$ npx oz init
$ npm i @openzeppelin/cli@rc
$ npx oz link @openzeppelin/contracts-ethereum-package
```
## Deploy (fails)
```
$ npx oz deploy
Nothing to compile, all contracts are up to date.
? Choose the kind of deployment upgradeable
? Pick a network development
? Pick a contract to deploy @openzeppelin/contracts-ethereum-package/StandaloneERC20
Contract undefined not found
```

**Comment by frangio** [comment]
This seems like an error in `oz create` in 2.8 RC as well.
