### ISSUE TITLE
can't fetch proxy contract admin by calling admin()

### ISSUE THREAD

**Issue by chenqping** [OpenZeppelin/openzeppelin-sdk#1501]
upgrades version 2.5.3

  /**
   * @return The address of the proxy admin.
   */
  function admin() external ifAdmin returns (address) {
    return _admin();
  }
this call didn't return admin address on Remix, but the gas was deducted

**Comment by abcoathup** [comment]
Hi @chenqping!  

Thanks for your question. I have posted it in the Community Forum, where it can get a faster response by the community and the team. I will close this issue so we can continue the discussion there!

https://forum.openzeppelin.com/t/cant-fetch-proxy-contract-admin-by-calling-admin/2443

**Comment by abcoathup** [comment]
Hi @chenqping,
This question has been answered in the Community Forum:
https://forum.openzeppelin.com/t/cant-fetch-proxy-contract-admin-by-calling-admin/2443
