### ISSUE TITLE
Explore upgradeability patterns using CREATE2

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#152]
In the [last core devs meeting](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2047.md#constantinople) it was mentioned that CREATE2 could be used to redeploy a contract at the same address updating its code, though at the cost of losing all balance and storage:

> Because of the way the contract address is calculated in CREATE2, which includes msg.sender, some salt, and the hash of the init code, it means that as long as the init code, salt, and msg.sender stay the same, you can redeploy the contract
> If init code loads deployed code from somewhere else, gives potential to instantiate contract with different code at same address

This would enable centralized upgrades by updating directly the **logic contract**, and storage could be preserved in a minimal proxy instead of an upgradeable proxy. The immediate benefit of this is in terms of gas: the minimal proxy is not just a lot cheaper to deploy, but introduces very little overhead in every call (since the target address is hardcoded, and it doesn't require an SLOAD on very call).

In terms of upgradeability governance, this means that the decision to upgrade relies on the owner of the logic contract, as the proxies would no longer have an owner. While this approach is not viable for on-chain libs, it may be appealing for apps, as it allows to upgrade all contracts in a single sweep.

The main downside is that upgrading a contract this way requires to destroy it, wait a block, and then upload the new version, hence it implies a downtime of a few blocks.

This could also be used to implement the issues on [chainable proxies](https://github.com/zeppelinos/zos/issues/11) and [upgradeable solidity libraries](https://github.com/zeppelinos/zos/issues/144).

**Comment by facuspagnuolo** [comment]
Loved the idea @spalladino, let's definitely do some research for it :)

**Comment by spalladino** [comment]
Implemented in #757
