### ISSUE TITLE
Could not retrieve solc releases list behind network proxy

### ISSUE THREAD

**Issue by kigawas** [OpenZeppelin/openzeppelin-sdk#1533]
When running `oz deploy` with a simple empty contract like
```solidity
pragma solidity ^0.5.0;

contract C {

}
```

It complains `Could not retrieve solc releases list: Client network socket disconnected before secure TLS connection was established`.

Any workaround to specify a local solc bin file or skip this? It'll be certainly better to make it work behind proxy but it'd require some efforts, so we may later handle that.

**Comment by abcoathup** [comment]
Hi @kigawas!  Thanks for your question. I have posted it in the Community Forum, where it can get a faster response by the community and the team. I will close this issue so we can continue the discussion there!

https://forum.openzeppelin.com/t/could-not-retrieve-solc-releases-list-behind-network-proxy/2816

**Comment by kigawas** [comment]
Looks like proxychains can also be a workaround.

**Comment by abcoathup** [comment]
Hi @kigawas,
I have posted an answer in the forum: https://forum.openzeppelin.com/t/openzeppelin-cli-could-not-retrieve-solc-releases-list-behind-network-proxy/2816/2?u=abcoathup
