### ISSUE TITLE
Provider not set or valid using zos-lib and truffle

### ISSUE THREAD

**Issue by James-Sangalli** [OpenZeppelin/openzeppelin-sdk#1561]
Hi All, Thanks for your great work in creating these tools!

When running a basic suite of tests using zos-lib and truffle I get the following error:

`Contract: Proxy
       "before each" hook: deploying legacy and upgradeable tokens for "has a name":
     Error: Provider not set or invalid`

this happens even if I am running a ganache local node on the correct port. 

Key details:

> node version v10.21.0
> zos-lib version ^2.4.3

Is this related to zos-lib or should I point my issue to truffle?

**Comment by spalladino** [comment]
Hey @James-Sangalli! Sorry to hear about that. Could you share a snippet of your code, to help diagnose the issue? Also, can you try out the latest `@openzeppelin/upgrades` library instead of the old `zos-lib`?

**Comment by spalladino** [comment]
Also, just in case, make sure you are initializing the library like this:
https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/examples/upgrades-library/index.js#L7

**Comment by James-Sangalli** [comment]
Hi @spalladino, thank you for your help.

I upgraded the library to your suggestion and ensured the web3 provider was set correctly. All is well now, cheers!
