### ISSUE TITLE
Creating an upgradable contract creates 3 transactions

### ISSUE THREAD

**Issue by thesolyd** [OpenZeppelin/openzeppelin-sdk#1563]
Hello,

When I deploy the Box.sol contract, it creates 3 transactions. I follow these instructions: https://docs.openzeppelin.com/learn/deploying-and-interacting#local-blockchain

Is it normal? I expect only one transaction to be deployed with 1 address. What are the other 2 addresses?

**Comment by frangio** [comment]
What you are likely seeing is the following three contracts:

1. The proxy itself
2. The implementation contract, that is the target of the proxy
3. A ProxyAdmin contract, that is used to upgrade the proxy

**Comment by thesolyd** [comment]
Many Thanks
