### ISSUE TITLE
Missing support for Solidity 0.7 in the @openzeppelin/upgrades package

### ISSUE THREAD

**Issue by andrekorol** [OpenZeppelin/openzeppelin-sdk#1580]
I've been using the '3.1.0-solc-0.7' version of the @openzeppelin/contracts package, which already supports compiling its contracts with solc 0.7.

But when I tried to inherit from a contract in the @openzeppelin/upgrades (Initializable.sol), I noticed that it still does not compile on solc 0.7 (it specifies 'pragma solidity >=0.4.24 <0.7.0;').

**Comment by abcoathup** [comment]
Hi @andrekorol!  I’m sorry that you had this issue.  

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.  

Just to let you know `Initializable` as part of the proxy contracts is being moved to OpenZeppelin Contracts: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2335

**Comment by andrekorol** [comment]
Hi @abcoathup, thanks for answering!  

If `Initializable` is already being moved to OpenZeppelin Contracts, then that's great since it already supports solc 0.7.

BTW, I love using the OpenZeppelin CLI, thank you for providing such a great product! :smiley:

**Comment by scorpion9979** [comment]
Thanks for bringing up this issue. This is also a blocker for me at the moment, as I'm heavily dependent on solc ^0.6.

**Comment by frangio** [comment]
A release candidate for the next version of OpenZeppelin Contracts has been published and it includes all the proxies as well as `Initializable`. [Check out the announcement in the forum!](https://forum.openzeppelin.com/t/openzeppelin-contracts-3-2-release-candidate/3718)

I'm closing this issue as we will not add Solidity 0.7 support in this project.
