### ISSUE TITLE
Error on oz verify ("Verification of regular instances is not yet supported.") 

### ISSUE THREAD

**Issue by Mehranh** [OpenZeppelin/openzeppelin-sdk#1585]
Hi 

When I want to verify my contract  by oz verify I get this error:

_Verification of regular instances is not yet supported._

But it works fine for oz deploy.

My scripts:
oz verify
? Pick a network mainnet
? Was your contract compiled with optimizations enabled? No
? Choose a remote endpoint etherscan
? Enter your Etherscan API key (get one at https://etherscan.io/myapikey) XXXXXXXXXXXXXXXXXXXXXXXX
? Pick a contract to verify CrToken
**Contract CrToken is not deployed to mainnet.
Verification of regular instances is not yet supported.**

**Comment by negati-ve** [comment]
same issue, 

can you help?
