### ISSUE TITLE
Tests are run only in a happy sync scenario 

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#170]
What?
The test suite would be more robust if it used a local network with non-zero blocktimes (i.e. the time for a block to be mined larger than zero).

Why?
The CLI performs a lot of async operations that are not fully tested when using a network that is almost synchronous like ganache with blocktime = 0. 

How?
I'm not sure exactly how to do this with Truffle, but it should be easy enough, and surely it should expose at least a couple of asynchronicity bugs.
Also, this should not be the default, but something that can be enabled manually or by CIs upon receiving new commits.

**Comment by spalladino** [comment]
@ajsantander this is implemented as integration tests (see https://github.com/zeppelinos/zos/tree/master/tests/cli-app). Do you think that covers this issue?

**Comment by ajsantander** [comment]
Looking at zos/test.sh I see that geth is run like this:
`nohup geth --dev --dev.period=1 --rpc --rpcport=9955 --rpcaddr=localhost --networkid 9955 > /dev/null &`

From geth's documentation:
--dev.period value  Block period to use in developer mode (0 = mine only if transaction pending) (default: 0)

Which suggests that you are using a blocktime of 1 instead of zero. If that is true, then this issue can be closed.

To be sure, I'd run a local test with:
`ganache-cli -b 1`
then
`npx truffle test --network local`

**Comment by spalladino** [comment]
Yep, integration tests are being with a period of 1 second. That said, it's only integration tests; doing the same for unit tests would be inviable in terms of running time.

**Comment by ajsantander** [comment]
Still, this would be valid for manual unit tests to be run every now and then.

**Comment by spalladino** [comment]
Gotcha. I think we can try running unit tests on a cron on a ganache with block period. Reopening!

**Comment by ajsantander** [comment]
After successfully running the tests locally with blocktime = 0, I get one error with blocktime = 1:
```
1) Contract: push script
       an app with dependency
         "before each" hook: deploying dependency for "should include deployment addresses":
     Error: Error: VM Exception while processing transaction: revert
      at sendTransaction (/home/ajs/zos/packages/lib/lib/utils/Transactions.js:40:70)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by spalladino** [comment]
Closing in favor of #173
