### ISSUE TITLE
Evaluate simplifying Initializable to work only for constructors

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#206]
From Nomic's v2.0.0 audit:

The current task of implementing an initializer can be confusing. [This warning](https://github.com/zeppelinos/zos/blob/6cd9a72b69902b50dead31f101c79b42211ee867/packages/lib/contracts/Initializable.sol#L12) recommends the initializers to either (1) don’t call parent’s initializers multiple times, or (2) be idempotent. 

My opinion is that asking for (1) is hopeless. Multiple inheritance is widely used in smart contracts, especially in OpenZeppelin, and makes it almost impossible to satisfy (1). If (2) were the only requirement for initializers, Initializable can be implemented as follows. 

```
modifier initializer() {
    require(isConstructor() , "Initializer can only be called during construction.");
    _;
}
```

This implementation has clearer semantics and rules out any possibility of re-initialization problems. Note that this proposal takes advantage of [this change to zOS](https://github.com/zeppelinos/zos/issues/100), which makes initializers callable during construction.

The main drawback of this is that idempotence is not a concept known by everyone. I don’t see any alternative that relaxes this restriction, with or without the proposed change.

**Comment by spalladino** [comment]
Closing as part of #1300
