### ISSUE TITLE
Error when checking for uninitialized base contracts

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#249]
The uninitialized base contract check (see #52) is failing even on simple cases with an `Cannot read property 'name' of undefined` error . Either identify the cause of the error and fix it, or remove the check altogether (drop L17 from `lib/src/validations/index.js`).

**Comment by Destiner** [comment]
Hi there! Want to try to tackle this, but can't launch zos from source.

I'm executing `node zos/packages/cli/src/bin/zos-cli.js`, but getting 
```
import { Logger } from 'zos-lib'
       ^

SyntaxError: Unexpected token {
```

**Comment by spalladino** [comment]
Removing feature altogether in #258 and moving this bug to backlog.

**Comment by Destiner** [comment]
Can you please provide an example that fails? I pushed some contracts and they seem to work fine. I ensured that "uninit base contract" check is running.

**Comment by spalladino** [comment]
Closing due to #1300
