### ISSUE TITLE
`ProxyCreated` event is not being emitted in unpublished projects

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#294]
We are not emitting the `ProxyCreated` event in unpublished projects (this event is triggered in the App contract). Because of this, we are losing track of created proxies and the `status --fetch/--fix` command won't work properly after publishing.  
Potential fix: https://github.com/zeppelinos/zos/issues/291.

**Comment by facuspagnuolo** [comment]
Related to https://github.com/zeppelinos/zos/issues/291

**Comment by spalladino** [comment]
Closing as status command is deprecated
