### ISSUE TITLE
Add troubleshooting section in docs

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#349]
We should create a new section like `troubleshooting` or so to address all the answers to the most common errors and questions we've been receiving. We can split this new section into multiple parts like installing, deploying, compiling/checking, testing, etc

**Comment by frangio** [comment]
We have the [FAQ](https://docs.openzeppelin.com/cli/faq) section which includes solutions for frequent problems. Any other frequent problems can go there too.
