### ISSUE TITLE
Install `zos` globally or use `npx`?

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#456]
Some parts of the documentation are guiding the user through installing the ZeppelinOS zos package globally, and other parts of the documentation are recommending the usage of `npx`. This may be confusing to a newcomer.

Should we pick one and be consistent?

**Comment by nventuro** [comment]
I like what [buidler has to say about this](https://github.com/nomiclabs/buidler#local-installation-recommended).

**Comment by spalladino** [comment]
Already being tackled by @nventuro
