### ISSUE TITLE
Programmatic guide could be more extensive

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#457]
The  documentation's "Using the ZeppelinOS programmatic library" at https://docs.zeppelinos.org/docs/zos_lib.html, shows the user how to use `Contracts` and `SimpleProject` from `zos-lib` in Javascript code.

This is super useful, but programmatic use can be much more extensive, and this should be documented.

For example, it does not explain the technique used in the vouching package's scripts, which also imports `zos` CLI elements like `scripts.push` or `scripts.session`.

Another alternative use can be seen in Brendan Asselstine's Integrating Zeppelin OS with Truffle article: https://medium.com/@asselstine/integrating-zeppelin-os-with-truffle-841e89fa34b3
In this case the `shelljs` package is used to call `zos` commands directly from the CLI as so:
```shell.exec(`zos create Migrations --init initialize --args ${accounts[0]} --network ${networkName} --from ${accounts[1]}`).code !== 0```

**Comment by spalladino** [comment]
Closing in favour of #1308
