### ISSUE TITLE
Evaluate simplifying lib exported Project models 

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#459]
Currently, we have 3 models: `AppProject`, `PackageProject`, `SimpleProject`, while app and package project models extend from `BasePackageProject` indeed.

`PackageProject` could be removed in favour of `AppProject`.
Additionally, evaluate merging cli's Deployer models into these project models

**Comment by pcowgill** [comment]
> Additionally, evaluate merging cli's Deployer models into these project models

This is covered by this issue https://github.com/zeppelinos/zos/issues/437

**Comment by pcowgill** [comment]
In the course of working on this issue, it would be nice if the eventual equivalent of `AppProject.fetchOrDeploy` provided a friendlier error message when trying to use a semver version of `0.0.0`. Right now the transaction triggered by this function reverts, and that's the main thing shown in the error message.

**Comment by spalladino** [comment]
Closing in favour of #1308

**Comment by pcowgill** [comment]
@spalladino Hmm, that issue seems to be about a different topic. This is about all of the project models.

**Comment by spalladino** [comment]
@pcowgill no worries, we will also re-assess the types of Projects we provide. `AppProject` is not being used a lot, and it may make sense to discontinue it, or at least simplify it. Thanks for keeping an eye on this!
