### ISSUE TITLE
TsMigration, Cli Phase 3: Syntax port of cli's test folders

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#485]
Following the migration plan from #434, port the tests code from Javascript to Typescript.

Note that the tests can currently run in Javascript just fine because we're using `ts-node`. This is achieved by using `require(ts-node/register)` in truffle-config.js.

- [ ] Port all the files to Ts.
- [ ] Unify tsconfig.json and tsconfig.test.json
- [ ] Remove ts-config TS_NODE_PROJECT environment variable from srcipts/test.sh

**Comment by spalladino** [comment]
Will not be doing this for now
