### ISSUE TITLE
Expose a flag to specify a compiler version

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#502]
Currently, if a user is working with Truffle we are relying on Truffle's compiler. If not, we are using our custom solc wrapper, in that case, currently there is no way for the user to specify an specific solc version, they will be compiling always with the last one.

We may also want to cover other solc settings like optimizer parameters, evm version, etc

**Comment by santanaruben** [comment]
Hello @facuspagnuolo I'm having an error when I compile with a different version,

![a](https://user-images.githubusercontent.com/39445525/51079260-737f2d80-169a-11e9-9e6c-d6fa7fa471c7.jpg)

I already set the compiler version in the truffle file configuration

![image](https://user-images.githubusercontent.com/39445525/51079294-f4d6c000-169a-11e9-9ccf-2d634c891914.png)

But I don't know if exist a flag for this, I can not see what I'm doing wrong, can you tell me what can I do.

Zos v2.0.2
Truffle v5.0.1 (core: 5.0.1)
Solidity - 0.5.2 (solc-js)
Node v10.15.0

**Comment by santanaruben** [comment]
Oh, nevermind, I just see this comment https://github.com/zeppelinos/zos/issues/540#issuecomment-449986367 when is fixed with the version v2.1.0-rc.0

**Comment by nventuro** [comment]
We now have `oz compile --solc-version`
