### ISSUE TITLE
Refactor commands layer

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#508]
In some CLI command declaration files we have some repeated content like:
- validating `options`
- compiling: `if (!options.skipCompile) await Compiler.call()`
- initialize config variables:  `await ConfigVariablesInitializer.initNetworkConfiguration(options)`
- weird exit logic: `if (!options.dontExitProcess && process.env.NODE_ENV !== 'test') process.exit(0)`

Analyze how these could be improved and centralized somehow

**Comment by frangio** [comment]
The groundwork for this has been laid out with the introduction of `register-command.ts`.
