### ISSUE TITLE
Support encoding of function types

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#560]
Pls see https://github.com/ethers-io/ethers.js/issues/389

Ethers.js/abi-coder is planning to support these types soon. Once they do, the dependency should be updated and a test should be added to `lib/test/src/helpers/encodeCall.test.js` to verify this.

**Comment by frangio** [comment]
Supporting function types at the CLI level would require _a lot_ of work beyond encoding the value, considering that these values are composed of the address of a target contract and an external function present at that contract, that has the same type as the function argument. I'm closing this until a strong use case shows up.
