### ISSUE TITLE
Extend tests on input.ts

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#568]
cli/src/utils/input.ts performs remix-like tests to parse incoming cli input and performs things such as:
- Wrap addresses and strings with quotes
- Expand scientific notation numbers to strings

Such parsing is tested in cli/test/src/utils/input.test.js, but they only test, IMHO, a few cases. They should be extended to be more exhaustive.

**Comment by spalladino** [comment]
Closing in favour of #981
