### ISSUE TITLE
Automate conversion to initializers

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-sdk#57]
Since normal constructors cannot be used in upgradeable contracts, users currently have to convert the constructors to initializer functions and use a mechanism like [`Initializable`](https://github.com/zeppelinos/zos/blob/master/packages/lib/contracts/migrations/Initializable.sol) to protect those functions.

This adds friction to the process of creating an upgradeable contract. We've been playing around with several ideas to automate this preprocessing and got down to two alternatives: 1) source code preprocessing to generate the initializer functions, 2) bytecode preprocessing to generate initializer contracts. This last idea grew out of the proposal in https://github.com/zeppelinos/zos-lib/issues/61.

There are some related experiments in the labs repo: [constructor without arguments](https://github.com/zeppelinos/labs/tree/master/initializer_contracts), [constructor with arguments but very inefficient](https://github.com/zeppelinos/labs/tree/master/initializer_contracts_with_args), and [source code preprocessing](https://github.com/zeppelinos/labs/tree/master/initializer_with_sol_editing).

**Comment by spalladino** [comment]
Closing in favour of #1300 :-)
