### ISSUE TITLE
Error 'Cannot read property 'bind' of undefined' when using TestHelper()

### ISSUE THREAD

**Issue by DavidMinarsch** [OpenZeppelin/openzeppelin-sdk#593]
First, thanks for an amazing project!

I have followed the instructions given here(https://docs.zeppelinos.org/docs/testing.html) to set up my project for testing with zos.

However, running `NODE_ENV=test npx truffle test` causes the following error:
<img width="732" alt="screen shot 2019-01-21 at 17 49 19" src="https://user-images.githubusercontent.com/19314578/51532903-49b3cc80-1e39-11e9-8a4f-32db64a2c7a7.png">

I'm using `node v10.15.0 (npm v6.6.0)` and my Truffle project (v5.0.0) dependencies are:
"zos": "^2.1.0",
"zos-lib": "^2.1.0"

test_file.js:
```
const zos = require('zos');
const ProofOfExistence = artifacts.require('../contracts/ProofOfExistence.sol');

contract('ProofOfExistence', (accounts) => {

....

  describe('ZOS upgradeability', () => {
    it('...should create a proxy', async function () {
      const project = await zos.TestHelper({ from: DEPLOYER_ADDRESS });
      const proxy = await project.createProxy(ProofOfExistence, { initMethod: 'initialize', initArgs: [BENEFICIARY_ADDRESS,PAUSER_ADDRESS], initFrom: DEPLOYER_ADDRESS});
      const result = await proxy.beneficiary();
      assert.equal(result, BENEFICIARY_ADDRESS, 'Returns incorrect beneficiary.');
    });
  });
});
```

Pointers in the right direction would be hugely appreciated!

**Comment by JirkaChadima** [comment]
Hi, stumbled upon the same behaviour today and I believe it's related to web3 version. zos 2.1.2 used the old v0.x line and if you're using web3 1.x, they don't speak to each other :(

I'm afraid the only solution is to either downgrade to web3 (for example, impossible for us), or upgrade to zos 2.2 and newer zos-lib

**Comment by spalladino** [comment]
Closing as it seems to be related to web3 version, now stabilized. Please reopen if that's not the case!
