### ISSUE TITLE
Migrate zos contracts to solidity v0.5.x

### ISSUE THREAD

**Issue by 0x3bfc** [OpenZeppelin/openzeppelin-sdk#598]
I tried to find if the issue is already exists or not, but it seems that there is no duplicates. 

Currently, I see that `zos-lib` contracts almost use `solidity v0.4.24`. It would be great if the solidity version can be migrated to [v0.5.x breaking changes](https://solidity.readthedocs.io/en/latest/050-breaking-changes.html).

**Comment by spalladino** [comment]
Agree! We actually have to migrate from truffle 4 to 5 for development first, but this comes right after that. Thanks for the feedback!!

**Comment by spalladino** [comment]
Implemented in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/ef03e13516855757b9bcfda6f0a8aab5534240db#diff-4c2060ba83bbf88924e4d2f83222f514. We may want to migrate to 0.6 now though!
