### ISSUE TITLE
Remove migrations folder

### ISSUE THREAD

**Issue by jeffanthony** [OpenZeppelin/openzeppelin-sdk#600]
Since the migrations folder is not used in zos I would love to see it removed.

I have seen it there, assumed truffle is involved and attempted truffle migrate just to check that out only to then discover there is no migrations.sol present. Not a huge deal but it might save man-minutes** on the dev-end.

Is there a reason this should not be done?

**Comment by spalladino** [comment]
The folder was originally there because truffle simply crashed on several commands (compile, test) if the folder was missing. We can check if the bug was fixed, and remove it if that's the case.

**Comment by spalladino** [comment]
Removed in d6ddc672836897ecde4c0e7167c4c5bb4e1a015c
