### ISSUE TITLE
Safer parsing of input

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#626]
In this PR https://github.com/zeppelinos/zos/pull/567, a few fixes were made to input.ts (remix-style parsing of input), and it was discussed that we could choose one of two safer approaches for a future iteration:

1. Be much more strict, and require everything to be properly enclosed in quotes (ie be valid JSON). This is more painful when accepting user input, but is a lot safer.
2. Generating a parser from a full grammar to handle the input, which should be safer and accommodate for more cases, but is also a lot more of work.

The current approach is not dangerous per-se, but uses non trivial regexes to parse all the input at once. There could be cases or situations that we are not accounting for.

**Comment by spalladino** [comment]
Closing in favour of #981
