### ISSUE TITLE
Avoid re-definition of the Web3 Contract interface in Contract.ts

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/openzeppelin-sdk#632]
Contract.ts declares the Contract interface, which is an extension of the Web3 Contract type. Since @types/web3 types Web3 Contract as a class, the current implementation re-writes the declaration as an interface, since Typescript cannot have an interface extend a class.

This could be problematic when web3 changes, since we would have to manually re-sync the Contract interface.

The solution to this issue might imply a change in ZeppelinOS, in Web3, or both.

**Comment by spalladino** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/28dbea4f8e9391fafbcdf2e75f458a7328508f67#diff-5ad4d2a04afaf11957783d6d44927310L16
