### ISSUE TITLE
Disallow creating a ZOS session when not at the top-level of project

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#646]
Currently, a for a global ZOS installation, calling` zos session ......` creates a zos.json file in whatever direction you call the command. Oversight leads to lots of hanging zos.json files around. Would be nice if the command only worked if you called from the top level of a ZOS project directly. Which is the only place it is actually effective, as the other ZOS commands seem to be directory-dependent.

**Comment by spalladino** [comment]
Running `oz session` anywhere now leads to `Could not find networks.js file, please remember to initialize your project.`
