### ISSUE TITLE
Fix lerna related issues

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#665]
Many of us have been facing different issues while using `lerna`. We are currently using version `~3.3.2`, but the latest version is currently `3.11.0`. Based on their [changelogs](https://github.com/lerna/lerna/releases), there were multiple bug fixes, so I'd try upgrading it to the latest version as a first step. 

Besides, this is the list of some of the issues I've been facing recently:
- Cleaning fails: running `npx lerna clean` fails the first time, but it succeeds if you try again.
- I've faced `missing property 0 of undefined` while installing `lerna` in the root dir
- Lib test script fails erratically due to not finding Truffle's module (see this [example](https://travis-ci.com/zeppelinos/zos/jobs/176811079#L489))
- Bootstrap for the integration tests fails erratically while bumping a new version (see [here](https://travis-ci.com/zeppelinos/zos/jobs/174590401#L1644))
- We need to run `lerna bootstrap` more than once to make sure deps are found by the CI (this may be a Travis issue - see `travis.yml` root file)
- Releasing is cumbersome: running `lerna version` does not update all the `package-lock` files. I need to update them using npm or re-running `lerna bootstrap` to make sure those are updated correctly. Thus, I never release using lerna automatically. 

Please feel free to comment/edit if some of you faced other issues.

**Comment by spalladino** [comment]
- `lerna bootstrap --scope=integration-test-workdir` does *not* symlink zos and zos-lib dependencies, since it only symlinks to projects in scope. It's fixed [for now](https://github.com/zeppelinos/zos/pull/668/files) by removing the scope, but it seems that running `lerna link` would be more efficient (though it does not `prepare` the dependencies).
