### ISSUE TITLE
Use web3 transactions timeout properly

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#680]
The `ZWeb3` wrapper implements a custom flow to deal with transactions timeout, we should use Web3's native one instead (see [transactionBlockTimeout](https://github.com/ethereum/web3.js/search?q=transactionBlockTimeout&unscoped_q=transactionBlockTimeout)).

Additionally, note that we are using users' session timeout to set that value. Those are different concepts, so please evaluate if it's necessary to introduce a new way to specify different values.

**Comment by spalladino** [comment]
Closing in favour of #1065
