### ISSUE TITLE
Review npm audit warnings

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#700]
Reported by Levi Morris.

![image](https://user-images.githubusercontent.com/429604/52905651-5b9b4c00-31fa-11e9-8b14-8779a7187707.png)

**Comment by abcoathup** [comment]
`truffle-config` has been updated to resolve (currently version 1.1.13 https://www.npmjs.com/package/truffle-config)
https://github.com/trufflesuite/truffle/pull/1708

Can `zos` and `zos-lib` version of `truffle-config` be updated?

**Comment by frangio** [comment]
All of the vulnerabilities that show up on `npm audit` at the moment are from web3 or its dependencies, and none of them have been patched yet, so short of removing the web3 dependency there is not much we can do.
