### ISSUE TITLE
Add tests for Contract (formerly ZosContract) class

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#712]
As the [Contract class](https://github.com/zeppelinos/zos/blob/master/packages/lib/src/artifacts/Contract.ts) is used throughout the project, we should consider adding unit tests for the `new`, `at` and `link` functions taking into account all possible scenarios: error throwing, args passed, options definition, return type/value etc.

**Comment by spalladino** [comment]
Closing due to age
