### ISSUE TITLE
Review commands descriptions

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#727]
Review all commands descriptions and evaluate whether or not they add useful information to the user.
For example, for the `init` command, "Provide a project-name" is already implied by its arguments:
```
Initialize your ZeppelinOS project. Provide a <project-name> and optionally an initial [version] name
```

Consider rewriting them to explain in a better way what the command does and try to avoid repeating already explained usage.

**Comment by spalladino** [comment]
Closing in favour of #875
