### ISSUE TITLE
Don't throw an error if the user provides a non-existent flag

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#733]
At this moment, if the user runs a command using a non-existent flag (for instance, `zos add --all --network local`), zos will throw the following error:
```sh
foo@bar:~$ zos add --all --network local 
error: unknown option `--network'
```
This could be somewhat annoying. We should be more flexible in these cases and just ignore the flag instead of throwing an error. An approach to fix this could be to use the `allowUnknownOption()` function provided by `commander.js`

**Comment by spalladino** [comment]
Disagree, let's fail if a command is incorrect. Also, this is less important having interactive mode running.
