### ISSUE TITLE
Run preceding commands under the hood instead of failing

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#752]
At this time, if the user runs, for instance, `zos add` or `zos push` before running `zos init`, the tool will fail and throw an error instead of asking to init the project, which could be somewhat annoying.
This same problem occurs in other scenarios where we should take into consideration and implement a *convention over configuration* workflow:

- If the user tries to update a proxy that does not exist, we should prompt them to first create it.
- If the user tries to create a proxy that has not been deployed, we should prompt them to push it.
- If the user tries to push contracts to a network and there are no contracts added in the `zos.json`, we should prompt them to  add them.
- It the user tries to add contracts before initializing the project, we should prompt them to initialize it.

The worst-case scenario could be if the user tries to update a proxy in a project that doesn't even exist. We should then prompt them to initialize it, to add contracts, to push them to a specific network, to create the proxy and finally update it.

**Comment by spalladino** [comment]
Implemented, except for initializing in advance, which make cause some issues
