### ISSUE TITLE
Review READMEs for all example projects

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#769]
Some projects in the `examples` folder lack a README explaining what they do, while [others](https://github.com/zeppelinos/zos/issues/702#issuecomment-469866427) may be a bit outdated.

Add a README for all the example projects that are missing it, and check the existing ones to ensure they are up-to-date.

**Comment by paulinablaszk** [comment]
I have recently analyzed the example of creating-instances-from-solidity so I decided to prepare a simple readme file for it. I hope it might be helpful for you.

**Comment by spalladino** [comment]
Closing as implemented. Thanks @paulinablaszk for your work!
