### ISSUE TITLE
Deploy dependencies on `create` if needed

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#777]
While making the `create` command interactive and playing around, `zos` threw me the following error:

```sh
foo@bar:~$ zos create openzeppelin-eth/StandaloneERC721 -n goerli

Dependency openzeppelin-eth has not been linked yet. Please run zos push.
```

Which is not 100% accurate as `openzeppelin-eth` was already linked (i.e., I runned `zos link openzeppelin-eth`) but not deployed on that network. The idea behind this issue is to discuss whether we should push all non-deployed dependencies while running `zos push` or `zos link`. In case we opt for the latter, we should take into consideration the following:
- If working against `ganache`, always deploy the dependencies
- If the package is already deployed on that network as a custom deploy or by the author, do nothing.
- If the package is not deployed on that network and it's not `ganache`, warn the user and ask them to deploy it.

Note that the items of this list have been already implemented in #706  :grinning: and that the idea would be to just move this logic to the `link` command.

**Comment by spalladino** [comment]
@jcarpanelli I'd avoid deploying on `link`, since `link` is a network-independent command, so we wouldn't know where to deploy.

That said, if we are now `push`ing a contract automatically when the user tries to create it, it makes sense to `push` the link to the dependency automatically as well upon create. WDYT?

**Comment by jcarpanelli** [comment]
Sorry for the late response :stuck_out_tongue:. I thought a bit more about this, and I concluded it makes sense to push the linked dependencies also when running `create`, but still feel that the `link` command should do everything (even if that means to change the `link` command behavior, and let it receive a network parameter). 
I'm happy with the solution you proposed though :) I'll see if I can include it in this sprint!

**Comment by spalladino** [comment]
Closing as we are reviewing the App structure
