### ISSUE TITLE
The create command with --args flag returns a regex error.

### ISSUE THREAD

**Issue by SamSteele01** [OpenZeppelin/openzeppelin-sdk#778]
In following the documentation on 
`https://docs.zeppelinos.org/docs/deploying.html` 

the command ( at the bottom of the page )
`npx zos create MyContract --init initialize --args 42,hitchhiker` 

fails and returns the error 
`Error parsing arguments: SyntaxError: Invalid regular expression: /(?<=^|([,[]\s*))(0[xX][0-9a-fA-F]+)(?=$|([,\]]\s*))/: Invalid group`

node 8.9.4
zos 2.2.1

**Comment by jcarpanelli** [comment]
Hey @SamSteele01, thank you for raising this! I've just tested it using `zos` `2.2.1` and `node` `8.9.4` and I'm experiencing the same error, but switching to node `v10.15.3` (LTS and [recommended version to use by node.js](https://nodejs.org/en/)) seems to be working fine. Could you please try again after updating node?

**Comment by siromivel** [comment]
I believe that on all pre-9.x Node versions RegEx lookbehind is only supported if the `--harmony` flag is passed - later versions should support them out of the box.

**Comment by SamSteele01** [comment]
So, switching to 10.15.3 did fix the problem for me. Good to know. Perhaps just mention it in the docs? I was on v8.9.4 at the recommendation of a different error.

**Comment by jcarpanelli** [comment]
> So, switching to 10.15.3 did fix the problem for me. Good to know. Perhaps just mention it in the docs? I was on v8.9.4 at the recommendation of a different error.

Great that you made it work :+1:. I'll keep this issue opened as we will probably look for a workaround to fix this the bug for older versions of `node` :slightly_smiling_face:. Thanks again for reporting it!

**Comment by spalladino** [comment]
Closing due to unmaintained version of node
