### ISSUE TITLE
Adding whitespaces in a list of comma-separated values in an option argument throws an error

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#783]
ATM, if you run a command that has an option that receives a list of comma-separated values as argument and you add whitespaces before or after the comma, for instance:
```sh
foo@bar:~$ zos create MyContract --init initialize --args 42, foo, bar
```
the following error will be thrown:

```sh
Error parsing arguments: SyntaxError: Unexpected token ] in JSON at position 6
    at parseArgs (/home/jota/work/zeppelin/zos/packages/cli/lib/utils/input.js:38:15)
    at Object.parseInit (/home/jota/work/zeppelin/zos/packages/cli/lib/utils/input.js:50:20)
    at Command.<anonymous> (/home/jota/work/zeppelin/zos/packages/cli/lib/commands/create.js:44:36)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jota/work/zeppelin/zos/packages/cli/lib/commands/create.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is because the `commander.js` `parse` function always expects a comma-separated list of values without spaces (for options), or otherwise it will interpret the second value as another `commander.js` option.

**Comment by PaulRBerg** [comment]
I just encountered this with `zos call`. The actual problem is that `zos call --help` yields the following output:

```
...
--args <arg1, arg2, ...>  arguments to the method to execute
...
```

There's a space between arg1 and arg2, which made me think that I should also add a space when providing the arguments for my call.

**Comment by JUDOKICK** [comment]
Reopening because I ran into this issue still in 10/08/2020 both ```--help``` and the sdk docs show the white spaced and I got an even more cryptic error "network name must be specified" event though I did specify explicitly. This fix should be simple. Edit the SDK docs and the help message.
