### ISSUE TITLE
ZWeb3 not working when using an url as provider

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#785]
ATM, when you initialize `ZWeb3` without a `web3` provider but with an url, zos fails to initialize the `web3` object, and the `ZWeb3#web3` method returns a `web3#HttpProvider` instead of a `web3` instance.

This should be very easy to fix: if `ZWeb3.provider` is an url/string, initialize a `web3#HttpProvider` and instead of returning it, return a new instance of `web3` using the provider initialized as parameter to the constructor.

**Comment by spalladino** [comment]
Fixed
