### ISSUE TITLE
Force users to sign a message using their private key for mission critical operations to prove their ownership

### ISSUE THREAD

**Issue by ylv-io** [OpenZeppelin/openzeppelin-sdk#796]
For mission critical operations on mainnet, like changing an owner of admin proxy. Force users to sign a message with their private key in order to verify that they own it in order to prevent transferring admin rights to a random address.
Probably wouldn’t work for multisig wallets.

**Comment by ylv-io** [comment]
Another idea proposed by @frangio is to use special kind of ownership which requires confirmation from the other side in order to fully claim rights. Essentially it puts ownership in a quasi state until it is confirmed by receiving party. If receiving party doesn't confirm it, it can be rolled back. That required multi-sig wallets to be able to issue specific transaction. Yet most of them can do that. And if not ownership is not lost. That seems as a best option so far.

**Comment by spalladino** [comment]
Closing in favour of #1229
