### ISSUE TITLE
Kickstart openzeppelin js

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#856]
Design the initial contents for openzeppelin js.

- Wrap GSN web3 provider to have transparent metatx support
- Allow to easily create web3 contract instances given the proxies deployed via zos (in both development in production, so we may not be able to leverage the hot-loader for this)
- Provide an easy way for starting and loading the web3 instance. Include the usual web3 intialization code (load metamask instance and enable it, or fall back to an infura node).
- Include React-based components (similar to redux's [Provider](https://redux.js.org/basics/usage-with-react#passing-the-store), [hooks](https://react-redux.js.org/next/api/hooks#useselector), or [connect](https://react-redux.js.org/next/using-react-redux/connect-mapstate#connect-extracting-data-with-mapstatetoprops)) for simplifying access to the web3 instance of any of the contracts.

**Comment by ylv-io** [comment]
workflowy
https://workflowy.com/s/openzeppelin-network/W8PA7jmaxmyVFwmm

**Comment by spalladino** [comment]
Clearly done https://github.com/OpenZeppelin/openzeppelin-network.js
