### ISSUE TITLE
Check the diff between two contract versions

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-sdk#87]
Currently, we are only working with version names, deployed bytecode and addresses in order to compare different contract versions. It could be a good idea to be able to see the diff between two versions of the same smart contract at a Solidity level. 

The solution to this problem could be also leveraged in order to work on https://github.com/zeppelinos/zos/issues/86

**Comment by frangio** [comment]
I think this is about the `status` subcommand that no longer exists.
