### ISSUE TITLE
zos push fails silently when web3 provider info is wrong

### ISSUE THREAD

**Issue by adikancherla** [OpenZeppelin/openzeppelin-sdk#891]
`zos push --skip-compile -v --network ropsten --from <addr>` was failing silently when my web3 provider info is wrong. For example, if using Infura as the provider and if Infura requires sending project secret (new in infura v3) with every request, not setting the secret correctly while configuring web3 provider in truffle config leads to infura requests failing. This failure should be printed out to stderr atleast while using -v flag. Failing silently helps no one.

**Comment by hickscorp** [comment]
This was also a problem for us today. We still havn't figured why ZOS returns, and how to use it with a `HDWalletProvider`.

For example, this is the output we get even tho we're calling `zos push --verbose`:

```
./scripts/bootstrap.sh
Operating on:
  Network: development
  Network ID: 5777
  Artifacts: zos.dev-5777.json
  Deployer: <OBFUSCATED>
  Governor: <OBFUSCATED>
yarn run v1.16.0
$ pwd/node_modules/.bin/zos push --verbose --network development
[Compiler] Compiling contracts with Truffle...

Compiling your contracts...
===========================
> Compiling ./contracts/Access.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Registry.sol
> Compiling ./contracts/Token.sol
> Compiling ./contracts/Transact.sol
> Compiling ./contracts/interfaces/AToken.sol
> Compiling ./contracts/interfaces/ATransact.sol
> Compiling ./contracts/lib/Accountable.sol
> Compiling ./contracts/lib/AddressSet.sol
> Compiling ./contracts/mocks/AccountableMock.sol
> Compiling ./contracts/mocks/TokenMock.sol
> Compiling ./contracts/mocks/TransactMock.sol
> Compiling ./node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol
> Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC20/IERC20.sol
> Compiling ./node_modules/zos-lib/contracts/Initializable.sol

> Artifacts written to pwd/build/contracts
> Compiled successfully using:
   - solc: 0.5.9+commit.e560f70d.Emscripten.clang


Done in 11.14s.
```

We have no idea what's up, as truffle actually connects using the same params.

**Comment by spalladino** [comment]
May be related to #997

**Comment by spalladino** [comment]
Closing: see [here](https://github.com/OpenZeppelin/openzeppelin-sdk/issues/997#issuecomment-565616894) for rationale.
