### ISSUE TITLE
Adding variables and functions when upgrading contracts

### ISSUE THREAD

**Issue by adikancherla** [OpenZeppelin/openzeppelin-sdk#912]
The documentation mentions that new variables should be added to the end of the contract when upgrading. Does this also apply to functions and events? I got validation errors on `zos push` when I tried to add a function in the middle. 

Does the `_____gap` array size needs to be adjusted when adding new variables, events and functions? For example, if I add a new function, should I resize the array to 49? Should new stuff be added after `_____gap` or before?

**Comment by spalladino** [comment]
Hey @nevverlander! Function and event definitions can be added (or removed) anywhere in a contract, as they don't take up storage space. Mind sharing which errors you are getting when adding functions?

As for the `__gap`, you should only resize it when adding new variables to your contract, not when adding functions or events. You can add new variables either before or after the gap (or even in the middle by splitting it in half!), though I'd suggest doing so before, just for clarity.

**Comment by nevverlander** [comment]
Here' s an example contract I created to reproduce the warnings:

```
pragma solidity ^0.5.8;

contract Test {

  uint256 a;

  function set() public {
    a = 10;
  }

  // Reserved storage space to allow for layout changes in the future.
  uint256[50] private ______gap;
}
```
Added it to zos.json with `zos add Test`, pushed it to ganache with `zos push` and created an instance using `zos create Test`. Then I updated it to add a function:

```
pragma solidity ^0.5.8;

contract Test {

  uint256 a;

  function set() public {
    a = 10;
  }

  function set2() public {
    a = 11;
  }

  // Reserved storage space to allow for layout changes in the future.
  uint256[50] private ______gap;
}
```
Now when I try to `zos push`, I get these warnings:
```
Validating contract Test
- New variable 'uint256[50] set2' was inserted in contract Test in contracts/Test.sol:1. You should only add new variables at the end of your contract.
See https://docs.zeppelinos.org/docs/writing_contracts.html#modifying-your-contracts for more info.
One or more contracts have validation errors. Please review the items listed above and fix them, or run this command again with the --force option.
```

**Comment by nevverlander** [comment]
Using zos version 2.2.3

**Comment by spalladino** [comment]
Could you clear `build/contracts` and try again from scratch using truffle 5.0.12 or earlier? I'm wondering if this could be related to [this issue](https://github.com/trufflesuite/truffle/issues/2048).

**Comment by nevverlander** [comment]
Ok - will try this when I get some time. Thanks.
