### ISSUE TITLE
Remove deprecated pages from docsite

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#917]
It seems that old pages are still accessible via their URL in the docsite (for instance, [building](https://docs.zeppelinos.org/docs/building.html)), which have completely outdated documentations and are super [confusing to new users](https://forum.zeppelin.solutions/t/could-not-find-zos-lib-contracts-migrations-migratable-sol-from-any-sources-when-following-tutorial/755).

We need to clean them up on every deployment. Consider either fixing the s3sync process, or switching to Netlify directly.

**Comment by frangio** [comment]
Fixed in the new docs site.
