### ISSUE TITLE
Documentation search doesn't show the version

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#922]
The documentation search doesn't show the version that a result relates to, which means the user could be directed to older versions of ZeppelinOS documentation.

Ideally the results would be ordered by version, with the latest version at the top.

<img width="886" alt="ZOS documentation" src="https://user-images.githubusercontent.com/28278242/58769321-426fad00-85e9-11e9-8eef-d2b90c5bc8cf.PNG">

**Comment by jcarpanelli** [comment]
This might be straightforward to fix. Adding the facetFilters: ["version:VERSION"] inside the algolia options in the `siteConfig.js` should do the trick. For more, see: https://docusaurus.io/docs/en/search#extra-search-options

**Comment by spalladino** [comment]
Closing in favour of https://github.com/OpenZeppelin/docs.openzeppelin.com/issues/15
