### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-sdk#925]
- [x] All package names
- [x] `zos` command line executable
- [x] Help and error texts in CLI
- [x] .zos.lock, .zos.session, zos.json and zos.network.json files (providing a migration path)
- [x] `.gitignore` contents
- [x] Imports of `zos-lib` and `zos` in all packages, tests, and examples
- [x] Imports of `zos-lib` contracts
- [x] `zosversion` field in `zos.json`
- [x] `zepkit` shorthand for `zos unpack` (rename to starter-kit)
- [x] Zos* functions and variables
- [x] Zos* source files and modules
- [x] Zos* functions and variables
- [ ] READMEs, HACKING, and other md files in the repo
- [x] All documentation _for next version_
- [x] Proxy storage slots, using [EIP 1967](https://github.com/ethereum/EIPs/pull/1967)
- [x] Mentions to EVM packages (now _Ethereum Packages_)
- [x] Rename starter kits
- [ ] Adjust starter kits contents to a new naming
- [x] Rename Hot Loader

**Comment by spalladino** [comment]
See https://github.com/zeppelinos/zos/pull/936 for a spec on the new names

**Comment by spalladino** [comment]
Consider moving Initializable to oz-eth and include oz-eth from zos-lib, so users can `import "@openzeppelin/contracts-eth/contracts/Initializable.sol" from oz-eth directly.

**Comment by ylv-io** [comment]
I suggest to renaming Zeppelin Solidity Hot Loader to openzeppelin-loader. Because it is a webpack loader and it is going to handle contract magic as well so that generic name will fit all the extra feature we want.

**Comment by ylv-io** [comment]
Are we killing zepkit.zeppelinos.org? Or we renaming it to something. SEO speaking it is better to have something like https://zeppelin.solutions/kits. I put a strong vote for that option.

**Comment by spalladino** [comment]
Fixed
