### ISSUE TITLE
zOS fails to install in Node 12

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-sdk#926]
In the process of reformatting my computer (OSX) and starting fresh I found that `zos` does not play well other the 'current' version of Node: v12.3.1 but rather needs version v10.16.0 to work correctly. 

The error messages I receive when trying to use the current version of Node: 

```
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dennison/.nvm/versions/node/v12.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/dennison/.nvm/versions/node/v12.3.1/bin/node" "/Users/dennison/.nvm/versions/node/v12.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dennison/Documents/my-project/node_modules/scrypt
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN my-project@1.0.0 No description
npm WARN my-project@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dennison/.npm/_logs/2019-05-31T18_51_59_446Z-debug.log
Dennisons-MacBook-Pro:my-project dennison$ 
```

This appears to be a problem with scrypt, but it quite a frustrating error. 

When running Node v10.16.0 this error was appearing on installs of ZOS and Truffle. 

```
Dennisons-MacBook-Pro:my-project dennison$ npm install zos
npm ERR! path /Users/dennison/Documents/my-project/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /Users/dennison/Documents/my-project/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /Users/dennison/Documents/my-project/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dennison/.npm/_logs/2019-05-31T18_56_24_258Z-debug.log
Dennisons-MacBook-Pro:my-project dennison$ 
```

This is an error that @nventuro told me happens to him also frequently and that the only solution appears to be running `rm -rf node_modules` and then doing `npm install` again. 

This error does not seem to be our fault, but it is very frustrating anyway.

**Comment by JirkaChadima** [comment]
I believe the Node 12 thing is the same thing as this https://github.com/trufflesuite/truffle/issues/2070

**Comment by spalladino** [comment]
@crazyrabbitLTC as you say there are two different issues involved here. I've created #929 to keep track of the error regarding "websocket", so let's follow the conversation on that one there.

Regarding node 12, there is nothing we can do at the moment, since this requires a change in the web3js library. However, as @gnidan points out [here](https://github.com/trufflesuite/truffle/issues/2070#issuecomment-498050438) and @alcuadrado [here](https://github.com/nomiclabs/buidler/pull/269#issuecomment-498075639), we are coordinating with the web3js team to get this situation resolved soon.

**Comment by mkhraisha** [comment]
@spalladino Web3 and truffle currently supports node 12, is there a reason this is still blocked?

**Comment by spalladino** [comment]
Nope, actually it has been working for several versions already - but we failed to close this issue. Thanks for the heads up!
