### ISSUE TITLE
Documentation on Proxy patterns has circular reference between docs and blog

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-sdk#935]
Proxy patterns documentation has a circular reference between the docs and the blog.

https://docs.zeppelinos.org/docs/pattern.html has a note at the top referencing a blog post:
> Note: For a more in depth read, please see blog.zeppelinos.org/proxy-patterns, which discusses the need for proxies, goes into more technical detail on the subject, elaborates on other possible proxy patterns that were considered for ZeppelinOS, and more.

But the blog post https://blog.zeppelinos.org/proxy-patterns/ has a note at the top pointing back to the same docs article:
> Update December 2018: Since this article was originally published, we have been working hard at ZeppelinOS on refining the proxy patterns we use on our libraries. Read here about the decisions we arrived at, and check out the ZeppelinOS audited implementation of those patterns.

**Comment by frangio** [comment]
There is no longer a circular reference but the link in the article is now broken.
