### ISSUE TITLE
Implement custom `zos` provider

### ISSUE THREAD

**Issue by jcarpanelli** [OpenZeppelin/openzeppelin-sdk#973]
Given that `zos` now has its own `networks.js` file (which can be modified any time), I was thinking that it would be nice to add a custom `zos` provider for managing connections to, for instance, infura using a mnemonic or a public key, which I believe is a very common way to connect to testnets/mainnet.

### What to do

We can add 2 new fields to the [Network Interface](https://github.com/zeppelinos/zos/blob/fe462009f403c655b92a1f2b96541dbd5e8bc718/packages/cli/src/models/config/ZosConfig.ts#L33): `infuraApiKey` and `mnemonic`/`privateKey` and end up having something like:

```js
  networks: {
    rinkeby: {
      infuraApiKey: 'f0758196cfd445c......e2fbb',
      mnemonic: 'jotola foo bar baz buz blabla....',
      gas: 5000000,
      gasPrice: 5e9,
      network_id: '*',
    },
    local: {
      protocol: 'http',
      host: 'localhost',
      port: 9545,
      gas: 5000000,
      gasPrice: 5e9,
      // eslint-disable-next-line @typescript-eslint/camelcase
      network_id: '4',
    },
  },
```

Zos will still support specifying the `protocol`, `host` and `port` fields, but if an `infuraApiKey` , `mnemonic` or `privateKey` is given, it will set the custom provider.

#### The easy way
The fastest and easiest way of accomplishing this is just installing `truffle-hdwallet-provider` in the `cli` and manually generate an instance of it when the infura api key and mnemonic/private key are provided.

#### The not so easy way
Create our own provider using [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine).

### But why?

- We will be removing a DX point of friction, which is telling the user to:
  - install `truffle-hdwallet-provider` 
  - import it in the `networks.js` 
  - set up the provider manually
- We will avoid referencing an external tool in our docsite.
- We will be giving a cleaner (and out of the box) solution for connecting to a testnet/mainnet.

**Comment by spalladino** [comment]
Consider using https://github.com/machinomy/hdwallet-provider as another alternative

**Comment by nventuro** [comment]
This can be very easily done by wrapping the http provider based on `host` and `port` with an `hdwallet-provider` if the `mnemonic` field is present in the config.

**Comment by frangio** [comment]
Closing this as it can already be achieved using hdwallet-provider in the config file.
